const JWT_SECRET_KEY = "12341234";
const USERS_TYPE = {
  TOURIST: "TOURIST",
  TAXI: "TAXI",
  AGENCY: "AGENCY",
  ADMIN: "ADMIN",
  HOTEL: "HOTEL",
};
module.exports = {
  JWT_SECRET_KEY,
  USERS_TYPE,
};
